### ISSUE TITLE
Fails to update specific inputs

### ISSUE THREAD

**Issue by lovesegfault** [cpcloud/flake-update-action#227]
Failed run: https://github.com/lovesegfault/nix-config/actions/runs/7168554123/job/19517011022

```
Run cpcloud/flake-update-action@v2.0.0
Run cpcloud/flake-dep-info-action@v2.0.10
Run nix flake update darwin
  nix flake update darwin
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    DETERMINATE_NIX_KVM: 0
error: cannot find flake 'flake:darwin' in the flake registries
Error: Process completed with exit code 1.
```

**Comment by sigprof** [comment]
This happens because since #220 the action uses the `nix flake update <dependency>` command, which requires Nix >= 2.19.0 (NixOS/nix#8817).

Annoyingly, that Nix change also broke the older `nix flake lock --update-input <dependency>` command at the same time,  and the backwards compatibility was restored only in NixOS/nix#9449 (master) and https://github.com/NixOS/nix/commit/819eda461556c0a886a945c8fdf517cb42f12213 (included in Nix 2.19.2).  So if you revert to the old version of this action to work around the incompatibility with older Nix versions, the action would fail if your Nix version happens to fall in the [2.19.0, 2.19.2) range.  The new Nix will also print deprecation warnings for the old command syntax; not sure when the old syntax will be removed completely.

**Comment by cpcloud** [comment]
I ... didn't realize anyone but me was using this :)

**Comment by cpcloud** [comment]
I can revert to the old syntax.

**Comment by sigprof** [comment]
At some point the old syntax would be removed, so the proper solution would probably be to detect the Nix version and use the new syntax on Nix >= 2.19.0 (at least until the older versions of Nix can be considered to be obsolete and not worth supporting).

Currently the latest stable NixOS version is 23.11, and it has Nix 2.18.1, which still uses the old syntax, therefore dropping the support for the old syntax is probably too early.
